# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.where(username: 'superadmin').first_or_create(username: 'superadmin', password: 'pwd12345', name: 'superadmin', role: 'superadmin')

bs=Unit.where(no: '20040002').first_or_create(name: '宝山区寄递事业部', short_name: '宝山区寄递事业部', level:1)
cm=Unit.where(no: '20210011').first_or_create(name: '崇明区寄递事业部', short_name: '崇明区寄递事业部', level:1)
fx=Unit.where(no: '20140015').first_or_create(name: '奉贤区寄递事业部', short_name: '奉贤区寄递事业部', level:1)
hk=Unit.where(no: '20040003').first_or_create(name: '虹口区寄递事业部', short_name: '虹口区寄递事业部', level:1)
hp=Unit.where(no: '20000546').first_or_create(name: '黄浦区寄递事业部', short_name: '黄浦区寄递事业部', level:1)
jd=Unit.where(no: '20180006').first_or_create(name: '嘉定区寄递事业部', short_name: '嘉定区寄递事业部', level:1)
js=Unit.where(no: '20050001').first_or_create(name: '金山区寄递事业部', short_name: '金山区寄递事业部', level:1)
ja=Unit.where(no: '20000244').first_or_create(name: '静安区区寄递事业部', short_name: '静安区区寄递事业部', level:1)
mh=Unit.where(no: '20110012').first_or_create(name: '闵行区寄递事业部', short_name: '闵行区寄递事业部', level:1)
pd=Unit.where(no: '20010002').first_or_create(name: '浦东新区寄递事业部', short_name: '浦东新区寄递事业部', level:1)
pt=Unit.where(no: '20000535').first_or_create(name: '普陀区寄递事业部', short_name: '普陀区寄递事业部', level:1)
qp=Unit.where(no: '20170010').first_or_create(name: '青浦区寄递事业部', short_name: '青浦区寄递事业部', level:1)
sj=Unit.where(no: '20160012').first_or_create(name: '松江区寄递事业部', short_name: '松江区寄递事业部', level:1)
xh=Unit.where(no: '20000242').first_or_create(name: '徐汇区寄递事业部', short_name: '徐汇区寄递事业部', level:1)
yp=Unit.where(no: '20000534').first_or_create(name: '杨浦区寄递事业部', short_name: '杨浦区寄递事业部', level:1)
cn=Unit.where(no: '20110014').first_or_create(name: '长宁区寄递事业部', short_name: '长宁区寄递事业部', level:1)

Unit.where(no: '20040013').first_or_create(name: '大场营业部', short_name: '大场速',  level:2, parent_id:bs.id)
Unit.where(no: '20040014').first_or_create(name: '泗塘营业部', short_name: '泗塘速',  level:2, parent_id:bs.id)
Unit.where(no: '20040015').first_or_create(name: '庙行营业部', short_name: '庙行速',  level:2, parent_id:bs.id)
Unit.where(no: '20190019').first_or_create(name: '杨行营业部', short_name: '杨行速',  level:2, parent_id:bs.id)
Unit.where(no: '20190024').first_or_create(name: '刘行营业部', short_name: '刘行速',  level:2, parent_id:bs.id)
Unit.where(no: '20090003').first_or_create(name: '月浦营业部', short_name: '月浦速',  level:2, parent_id:bs.id)
Unit.where(no: '20044404').first_or_create(name: '聚丰园路营业部', short_name: '聚丰园路',  level:2, parent_id:bs.id)
Unit.where(no: '20044102').first_or_create(name: '淞南营业部', short_name: '淞南速',  level:2, parent_id:bs.id)
Unit.where(no: '20190007').first_or_create(name: '友谊路营业部', short_name: '友谊路速',  level:2, parent_id:bs.id)
Unit.where(no: '20190604').first_or_create(name: '顾村营业部', short_name: '顾村速',  level:2, parent_id:bs.id)
Unit.where(no: '20190804').first_or_create(name: '罗南营业部', short_name: '罗南速',  level:2, parent_id:bs.id)
Unit.where(no: '20210021').first_or_create(name: '庙镇营业部', short_name: '庙镇速递', level:2, parent_id:cm.id)
Unit.where(no: '20210026').first_or_create(name: '堡镇营业部', short_name: '堡镇速递', level:2, parent_id:cm.id)
Unit.where(no: '20190034').first_or_create(name: '长兴营业部', short_name: '长兴速递', level:2, parent_id:cm.id)
Unit.where(no: '20190035').first_or_create(name: '横沙营业部', short_name: '横沙速递', level:2, parent_id:cm.id)
Unit.where(no: '20215008').first_or_create(name: '崇明营业部', short_name: '崇明速递', level:2, parent_id:cm.id)
Unit.where(no: '20140032').first_or_create(name: '肖塘营业部', short_name: '肖塘速', level:2, parent_id:fx.id)
Unit.where(no: '20140044').first_or_create(name: '金汇营业部', short_name: '金汇速', level:2, parent_id:fx.id)
Unit.where(no: '20140037').first_or_create(name: '泰日营业部', short_name: '泰日速', level:2, parent_id:fx.id)
Unit.where(no: '20140028').first_or_create(name: '庄行营业部', short_name: '庄行速', level:2, parent_id:fx.id)
Unit.where(no: '20140029').first_or_create(name: '柘林营业部', short_name: '柘林速', level:2, parent_id:fx.id)
Unit.where(no: '20140046').first_or_create(name: '海湾营业部', short_name: '海湾速', level:2, parent_id:fx.id)
Unit.where(no: '20140047').first_or_create(name: '奉城营业部', short_name: '奉城速', level:2, parent_id:fx.id)
Unit.where(no: '20140042').first_or_create(name: '平安营业部', short_name: '平安速', level:2, parent_id:fx.id)
Unit.where(no: '20140014').first_or_create(name: '南桥营业部', short_name: '南桥速', level:2, parent_id:fx.id)
Unit.where(no: '20141402').first_or_create(name: '青村营业部', short_name: '青村速', level:2, parent_id:fx.id)
Unit.where(no: '20000522').first_or_create(name: '虹口营业部', short_name: '虹口速', level:2, parent_id:hk.id)
Unit.where(no: '20040021').first_or_create(name: '车站北路营业部', short_name: '车站北速', level:2, parent_id:hk.id)
Unit.where(no: '20008605').first_or_create(name: '飞虹路营业部', short_name: '飞虹路速', level:2, parent_id:hk.id)
Unit.where(no: '20008210').first_or_create(name: '提篮桥营业部', short_name: '提篮桥', level:2, parent_id:hk.id)
Unit.where(no: '20043406').first_or_create(name: '凉城路营业部', short_name: '凉城路速', level:2, parent_id:hk.id)
Unit.where(no: '20000214').first_or_create(name: '外滩营业部', short_name: '外滩', level:2, parent_id:hp.id)
Unit.where(no: '20001010').first_or_create(name: '豫园营业部', short_name: '豫园', level:2, parent_id:hp.id)
Unit.where(no: '20002008').first_or_create(name: '新天地营业部', short_name: '新天地', level:2, parent_id:hp.id)
Unit.where(no: '20002506').first_or_create(name: '马当路营业部', short_name: '马当路', level:2, parent_id:hp.id)
Unit.where(no: '20180026').first_or_create(name: '马陆营业部', short_name: '马陆速', level:2, parent_id:jd.id)
Unit.where(no: '20180029').first_or_create(name: '黄渡营业部', short_name: '黄渡速', level:2, parent_id:jd.id)
Unit.where(no: '20180024').first_or_create(name: '外冈营业部', short_name: '外冈速', level:2, parent_id:jd.id)
Unit.where(no: '20181402').first_or_create(name: '安亭营业部', short_name: '安亭速', level:2, parent_id:jd.id)
Unit.where(no: '20180018').first_or_create(name: '南翔营业部', short_name: '南翔揽投', level:2, parent_id:jd.id)
Unit.where(no: '20181804').first_or_create(name: '嘉定新城营业部', short_name: '嘉新城速', level:2, parent_id:jd.id)
Unit.where(no: '20182105').first_or_create(name: '嘉定工业区营业部', short_name: '工业区速', level:2, parent_id:jd.id)
Unit.where(no: '20182403').first_or_create(name: '曹安营业部', short_name: '曹安速', level:2, parent_id:jd.id)
Unit.where(no: '20180031').first_or_create(name: '丰庄营业部', short_name: '丰庄速', level:2, parent_id:jd.id)
Unit.where(no: '20180033').first_or_create(name: '城中路营业部', short_name: '城中路速', level:2, parent_id:jd.id)
Unit.where(no: '20150019').first_or_create(name: '漕泾营业部', short_name: '漕泾营业', level:2, parent_id:js.id)
Unit.where(no: '20150011').first_or_create(name: '山阳营业部', short_name: '山阳营业', level:2, parent_id:js.id)
Unit.where(no: '20150018').first_or_create(name: '枫泾营业部', short_name: '枫泾速', level:2, parent_id:js.id)
Unit.where(no: '20150009').first_or_create(name: '亭林营业部', short_name: '亭林速', level:2, parent_id:js.id)
Unit.where(no: '20150015').first_or_create(name: '廊下营业部', short_name: '廊下速', level:2, parent_id:js.id)
Unit.where(no: '20150017').first_or_create(name: '干巷营业部', short_name: '干巷速', level:2, parent_id:js.id)
Unit.where(no: '20054005').first_or_create(name: '石化营业部', short_name: '石化', level:2, parent_id:js.id)
Unit.where(no: '20150004').first_or_create(name: '朱泾营业部', short_name: '朱泾速', level:2, parent_id:js.id)
Unit.where(no: '20004205').first_or_create(name: '静安营业部', short_name: '静安速', level:2, parent_id:ja.id)
Unit.where(no: '20000308').first_or_create(name: '南京西路营业部', short_name: '南京西速', level:2, parent_id:ja.id)
Unit.where(no: '20007015').first_or_create(name: '沪太路营业部', short_name: '虬江路揽', level:2, parent_id:ja.id)
Unit.where(no: '20043610').first_or_create(name: '聚能湾营业部', short_name: '聚能湾', level:2, parent_id:ja.id)
Unit.where(no: '20008509').first_or_create(name: '上海站营业部', short_name: '上海站', level:2, parent_id:ja.id)
Unit.where(no: '20007212').first_or_create(name: '大宁营业部', short_name: '大宁', level:2, parent_id:ja.id)
Unit.where(no: '20000593').first_or_create(name: '万航渡路', short_name: '万航渡速', level:2, parent_id:ja.id)
Unit.where(no: '20110043').first_or_create(name: '马桥营业部', short_name: '马桥速', level:2, parent_id:mh.id)
Unit.where(no: '20110045').first_or_create(name: '虹桥营业部', short_name: '虹桥速', level:2, parent_id:mh.id)
Unit.where(no: '20110049').first_or_create(name: '陈行营业部', short_name: '陈行速', level:2, parent_id:mh.id)
Unit.where(no: '20110039').first_or_create(name: '伟业路营业部', short_name: '伟业路速', level:2, parent_id:mh.id)
Unit.where(no: '20110506').first_or_create(name: '航华营业部', short_name: '航华速', level:2, parent_id:mh.id)
Unit.where(no: '20020024').first_or_create(name: '莲花路营业部', short_name: '莲花揽投', level:2, parent_id:mh.id)
Unit.where(no: '20024103').first_or_create(name: '吴泾营业部', short_name: '吴泾', level:2, parent_id:mh.id)
Unit.where(no: '20024503').first_or_create(name: '东川营业部', short_name: '东川速', level:2, parent_id:mh.id)
Unit.where(no: '20110008').first_or_create(name: '莘庄营业部', short_name: '莘庄速', level:2, parent_id:mh.id)
Unit.where(no: '20110027').first_or_create(name: '古美营业部', short_name: '古美速', level:2, parent_id:mh.id)
Unit.where(no: '20110038').first_or_create(name: '鲁汇营业部', short_name: '鲁汇速', level:2, parent_id:mh.id)
Unit.where(no: '20110110').first_or_create(name: '漕宝路营业部', short_name: '漕宝路速', level:2, parent_id:mh.id)
Unit.where(no: '20110602').first_or_create(name: '华漕营业部', short_name: '华漕速', level:2, parent_id:mh.id)
Unit.where(no: '20110808').first_or_create(name: '田园营业部', short_name: '田园速', level:2, parent_id:mh.id)
Unit.where(no: '20111204').first_or_create(name: '浦江镇营业部', short_name: '浦江镇速', level:2, parent_id:mh.id)
Unit.where(no: '20120020').first_or_create(name: '合庆营业部', short_name: '合庆速', level:2, parent_id:pd.id)
Unit.where(no: '20010023').first_or_create(name: '世博营业部', short_name: '世博速', level:2, parent_id:pd.id)
Unit.where(no: '20120025').first_or_create(name: '江镇营业部', short_name: '江镇速', level:2, parent_id:pd.id)
Unit.where(no: '20130021').first_or_create(name: '周浦营业部', short_name: '周浦速', level:2, parent_id:pd.id)
Unit.where(no: '20010020').first_or_create(name: '永泰路营业部', short_name: '永泰路速', level:2, parent_id:pd.id)
Unit.where(no: '20130025').first_or_create(name: '惠南营业部', short_name: '惠南速', level:2, parent_id:pd.id)
Unit.where(no: '20130020').first_or_create(name: '祝桥营业部', short_name: '祝桥速', level:2, parent_id:pd.id)
Unit.where(no: '20010021').first_or_create(name: '塘桥营业部', short_name: '塘桥速', level:2, parent_id:pd.id)
Unit.where(no: '20130023').first_or_create(name: '金桥营业部', short_name: '金桥速', level:2, parent_id:pd.id)
Unit.where(no: '20012109').first_or_create(name: '陆家嘴营业部', short_name: '陆家嘴速', level:2, parent_id:pd.id)
Unit.where(no: '20012209').first_or_create(name: '浦电路营业部', short_name: '浦电路速', level:2, parent_id:pd.id)
Unit.where(no: '20013511').first_or_create(name: '联洋营业部', short_name: '联洋速', level:2, parent_id:pd.id)
Unit.where(no: '20012506').first_or_create(name: '南码头营业部', short_name: '南码头速', level:2, parent_id:pd.id)
Unit.where(no: '20013605').first_or_create(name: '金杨营业部', short_name: '金杨速', level:2, parent_id:pd.id)
Unit.where(no: '20120409').first_or_create(name: '花木营业部', short_name: '花木速', level:2, parent_id:pd.id)
Unit.where(no: '20120309').first_or_create(name: '科创中心营业部', short_name: '科创中心', level:2, parent_id:pd.id)
Unit.where(no: '20012403').first_or_create(name: '三林营业部', short_name: '三林速', level:2, parent_id:pd.id)
Unit.where(no: '20120608').first_or_create(name: '博兴营业部', short_name: '博兴速', level:2, parent_id:pd.id)
Unit.where(no: '20120016').first_or_create(name: '张江营业部', short_name: '张江营业', level:2, parent_id:pd.id)
Unit.where(no: '20131505').first_or_create(name: '康桥营业部', short_name: '康桥速', level:2, parent_id:pd.id)
Unit.where(no: '20013104').first_or_create(name: '自贸区营业部', short_name: '自贸区速', level:2, parent_id:pd.id)
Unit.where(no: '20120906').first_or_create(name: '曹路营业部', short_name: '曹路速', level:2, parent_id:pd.id)
Unit.where(no: '20120207').first_or_create(name: '川沙新镇营业部', short_name: '川新速', level:2, parent_id:pd.id)
Unit.where(no: '20131404').first_or_create(name: '新场镇营业部', short_name: '新场镇速', level:2, parent_id:pd.id)
Unit.where(no: '20130607').first_or_create(name: '临港新城营业部', short_name: '临港速', level:2, parent_id:pd.id)
Unit.where(no: '20131805').first_or_create(name: '航头营业部', short_name: '航头', level:2, parent_id:pd.id)
Unit.where(no: '20130022').first_or_create(name: '外高桥营业部', short_name: '高桥速', level:2, parent_id:pd.id)
Unit.where(no: '20000588').first_or_create(name: '常德路营业部', short_name: '常德路速', level:2, parent_id:pt.id)
Unit.where(no: '20000591').first_or_create(name: '长征营业部', short_name: '长征速', level:2, parent_id:pt.id)
Unit.where(no: '20006005').first_or_create(name: '新村路营业部', short_name: '新村路速', level:2, parent_id:pt.id)
Unit.where(no: '20006208').first_or_create(name: '云岭营业部', short_name: '云岭', level:2, parent_id:pt.id)
Unit.where(no: '20006305').first_or_create(name: '武宁路营业部', short_name: '武宁路', level:2, parent_id:pt.id)
Unit.where(no: '20033106').first_or_create(name: '桃浦营业部', short_name: '桃浦', level:2, parent_id:pt.id)
Unit.where(no: '20033310').first_or_create(name: '真如营业部', short_name: '真如', level:2, parent_id:pt.id)
Unit.where(no: '20170033').first_or_create(name: '练塘营业部', short_name: '练塘速', level:2, parent_id:qp.id)
Unit.where(no: '20170034').first_or_create(name: '金泽营业部', short_name: '金泽速', level:2, parent_id:qp.id)
Unit.where(no: '20170036').first_or_create(name: '凤溪营业部', short_name: '凤溪营业', level:2, parent_id:qp.id)
Unit.where(no: '20170007').first_or_create(name: '青浦新城营业部', short_name: '青新城速', level:2, parent_id:qp.id)
Unit.where(no: '20170008').first_or_create(name: '香花桥营业部', short_name: '香花桥速', level:2, parent_id:qp.id)
Unit.where(no: '20170202').first_or_create(name: '徐泾营业部', short_name: '徐泾', level:2, parent_id:qp.id)
Unit.where(no: '20171304').first_or_create(name: '朱家角营业部', short_name: '朱家角速', level:2, parent_id:qp.id)
Unit.where(no: '20170027').first_or_create(name: '赵巷营业部', short_name: '赵巷速', level:2, parent_id:qp.id)
Unit.where(no: '20170038').first_or_create(name: '白鹤营业部', short_name: '白鹤速', level:2, parent_id:qp.id)
Unit.where(no: '20160026').first_or_create(name: '泗泾营业部', short_name: '泗泾揽投', level:2, parent_id:sj.id)
Unit.where(no: '20160041').first_or_create(name: '洞泾营业部', short_name: '洞泾营业', level:2, parent_id:sj.id)
Unit.where(no: '20160037').first_or_create(name: '人民路营业部', short_name: '人民路速', level:2, parent_id:sj.id)
Unit.where(no: '20160050').first_or_create(name: '陈坊桥营业部', short_name: '陈坊桥速', level:2, parent_id:sj.id)
Unit.where(no: '20160036').first_or_create(name: '石湖荡营业部', short_name: '石湖荡速', level:2, parent_id:sj.id)
Unit.where(no: '20160038').first_or_create(name: '泖港营业部', short_name: '泖港速', level:2, parent_id:sj.id)
Unit.where(no: '20160029').first_or_create(name: '叶榭营业部', short_name: '叶榭速', level:2, parent_id:sj.id)
Unit.where(no: '20160043').first_or_create(name: '车墩营业部', short_name: '车墩速', level:2, parent_id:sj.id)
Unit.where(no: '20160032').first_or_create(name: '小昆山营业部', short_name: '小昆山速', level:2, parent_id:sj.id)
Unit.where(no: '20161202').first_or_create(name: '新桥营业部', short_name: '新桥速', level:2, parent_id:sj.id)
Unit.where(no: '20161310').first_or_create(name: '九亭营业部', short_name: '九亭', level:2, parent_id:sj.id)
Unit.where(no: '20162004').first_or_create(name: '松江新城营业部', short_name: '松新城速', level:2, parent_id:sj.id)
Unit.where(no: '20169901').first_or_create(name: '东开营业部', short_name: '东开速', level:2, parent_id:sj.id)
Unit.where(no: '20020033').first_or_create(name: '龙华营业部', short_name: '支局龙华', level:2, parent_id:xh.id)
Unit.where(no: '20000557').first_or_create(name: '淮海中路营业部', short_name: '淮海中路', level:2, parent_id:xh.id)
Unit.where(no: '20020034').first_or_create(name: '华泾路营业部', short_name: '华泾路营', level:2, parent_id:xh.id)
Unit.where(no: '20020031').first_or_create(name: '习勤路营业部', short_name: '习勤速', level:2, parent_id:xh.id)
Unit.where(no: '20003022').first_or_create(name: '徐家汇营业部', short_name: '徐家汇', level:2, parent_id:xh.id)
Unit.where(no: '20003207').first_or_create(name: '东安路营业部', short_name: '东安路', level:2, parent_id:xh.id)
Unit.where(no: '20023310').first_or_create(name: '漕河泾营业部', short_name: '漕河泾速', level:2, parent_id:xh.id)
Unit.where(no: '20023711').first_or_create(name: '梅陇营业部', short_name: '梅陇', level:2, parent_id:xh.id)
Unit.where(no: '20000575').first_or_create(name: '鞍山路营业部', short_name: '鞍山路', level:2, parent_id:yp.id)
Unit.where(no: '20040023').first_or_create(name: '民星营业部', short_name: '民星营业', level:2, parent_id:yp.id)
Unit.where(no: '20009211').first_or_create(name: '铁岭路营业部', short_name: '铁岭路', level:2, parent_id:yp.id)
Unit.where(no: '20009010').first_or_create(name: '杨浦营业部', short_name: '杨浦', level:2, parent_id:yp.id)
Unit.where(no: '20043310').first_or_create(name: '五角场营业部', short_name: '五角场', level:2, parent_id:yp.id)
Unit.where(no: '20033510').first_or_create(name: '北新泾营业部', short_name: '北新泾', level:2, parent_id:cn.id)
Unit.where(no: '20005007').first_or_create(name: '长宁营业部', short_name: '长宁速', level:2, parent_id:cn.id)
Unit.where(no: '20005110').first_or_create(name: '天山营业部', short_name: '天山', level:2, parent_id:cn.id)
Unit.where(no: '20033613').first_or_create(name: '古北营业部', short_name: '古北', level:2, parent_id:cn.id)


Business.where(code: '90000006961440').first_or_create(name: '身份证到付', btype: '身份证个邮', industry: '户政类', time_limit: 36)
Business.where(code: '90000009822326').first_or_create(name: '派出所直配', btype: '身份证打包', industry: '户政类', time_limit: 36)
Business.where(code: '91100015649119').first_or_create(name: '港澳台居住证到付', btype: '身份证个邮', industry: '户政类', time_limit: 36)
Business.where(code: '91100242644756').first_or_create(name: '户政材料', btype: '户籍', industry: '户政类', time_limit: 36)
Business.where(code: '90000010296749').first_or_create(name: '出入境新证', btype: '出入境个人', industry: '出入境', time_limit: 36)
Business.where(code: '90000011041692').first_or_create(name: '出入境4元', btype: '出入境个人', industry: '出入境', time_limit: 36)
Business.where(code: '90000011041715').first_or_create(name: '出入境6元', btype: '出入境个人', industry: '出入境', time_limit: 36)
Business.where(code: '31011511000090').first_or_create(name: '出入境管理局（港澳续签）', btype: '出入境续签', industry: '出入境', time_limit: 36)
Business.where(code: '91100016098938').first_or_create(name: '出入境派出所', btype: '出入境对公', industry: '出入境', time_limit: 36)
Business.where(code: '90000010351404').first_or_create(name: '车管到家单程（APP）', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '90000010351325').first_or_create(name: '车管到家返单（APP）', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '90000000559166').first_or_create(name: '车管到家揽收(发票）', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '90000011237329').first_or_create(name: '车管到家解抵押', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '90000011498003').first_or_create(name: '平安车险', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '90000011667113').first_or_create(name: '车管邮窗', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '91100001094017').first_or_create(name: '警医邮', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '91100035665928').first_or_create(name: '摩托车驾驶证', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '91100035665984').first_or_create(name: '一网通办六年免检', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '91100103746283').first_or_create(name: '驾哿企业管理', btype: '车管到家', industry: '交管类', time_limit: 36)
Business.where(code: '91100271068152').first_or_create(name: '帮困基金', btype: '总工会', industry: '社会组织', time_limit: 36)
Business.where(code: '31000014258000').first_or_create(name: '试卷运送', btype: '教育考试院', industry: '校园类', time_limit: 36)
Business.where(code: '90000011190147').first_or_create(name: '不动产', btype: '不动产', industry: '机关公文', time_limit: 36)
Business.where(code: '31011310020051').first_or_create(name: '车牌（淞南）', btype: '交管号牌', industry: '交管类', time_limit: 36)
Business.where(code: '31011290099000').first_or_create(name: '古北（网上车管）', btype: '网上车管', industry: '交管类', time_limit: 36)
Business.where(code: '1100038944303').first_or_create(name: '宝山区行政服务中心（一程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100115197488').first_or_create(name: '宝山区行政服务中心（二程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100043771611').first_or_create(name: '黄浦区行政服务中心（一程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '90000011572512').first_or_create(name: '黄浦区行政服务中心（二程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100030978863').first_or_create(name: '黄浦区行政服务中心（返单）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100038938609').first_or_create(name: '青浦区行政服务中心（一程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100037163417').first_or_create(name: '青浦区行政服务中心（二程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100049541454').first_or_create(name: '虹口区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100040804514').first_or_create(name: '杨浦区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100043784121').first_or_create(name: '徐汇区行政服务中心（一程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100024283663').first_or_create(name: '徐汇区行政服务中心（二程）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100053564702').first_or_create(name: '长宁区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100055049814').first_or_create(name: '崇明区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100039923705').first_or_create(name: '静安区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100037163361').first_or_create(name: '奉贤区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100001530045').first_or_create(name: '闵行区证照中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100012905964').first_or_create(name: '普陀区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100059467205').first_or_create(name: '嘉定区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100058183647').first_or_create(name: '松江区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100059467025').first_or_create(name: '浦东市民中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100053564959').first_or_create(name: '金山区行政服务中心', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100020510639').first_or_create(name: '上海市社团局', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100034609789').first_or_create(name: '大数据中心（到付）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '91100034609666').first_or_create(name: '大数据中心（寄付）', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '1100043736779').first_or_create(name: '上海市药监局', btype: '一网通办', industry: '机关公文', time_limit: 36)
Business.where(code: '90000005683765').first_or_create(name: '浦东新区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '90000005683765').first_or_create(name: '浦东自贸区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '90000010039182').first_or_create(name: '嘉定区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043750898').first_or_create(name: '金山区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043785526').first_or_create(name: '青浦区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100030978863').first_or_create(name: '黄浦区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043812448').first_or_create(name: '长宁区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '9000010640764').first_or_create(name: '虹口区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043785548').first_or_create(name: '宝山区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043775480').first_or_create(name: '静安区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043812437').first_or_create(name: '奉贤区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043747962').first_or_create(name: '徐汇区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100039166322').first_or_create(name: '松江区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043782477').first_or_create(name: '崇明区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043769685').first_or_create(name: '杨浦区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043759662').first_or_create(name: '闵行区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100043812415').first_or_create(name: '普陀区税务局', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '1100044097332').first_or_create(name: '税务三分所', btype: '发票寄递', industry: '税务类', time_limit: 36)
Business.where(code: '90000011572523').first_or_create(name: '催报文书', btype: '涉税文书', industry: '税务类', time_limit: 36)


